apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali-httproute
  namespace: istio-system
spec:
  parentRefs:
    - name: main
      namespace: gateway-system
      sectionName: https
  hostnames: 
    - "kiali.technologylab.uk"
  rules:
    - backendRefs:
        - name: kiali-server
          port: 80