apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:danyalahmed/dac-lab-private.git
    path: kubernetes/infra/cert-manager-issuers
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
