apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    repoURL: https://cloudnative-pg.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.0
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
