apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: homeautomation
  source:
    repoURL: git@github.com:danyalahmed/dac-lab-private.git
    path: kubernetes/infra/homeassistant
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: homeautomation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
