---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    repoURL: https://seaweedfs.github.io/seaweedfs-operator
    chart: seaweedfs-operator
    targetRevision: 0.1.12

  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: seaweedfs
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   project: infrastructure
#   source:
#     repoURL: https://github.com/danyalahmed/dac-lab.git
#     path: kubernetes/infra/seaweedfs

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: shared-services

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# secondary instance used only for PG backups (breakglass)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-cluster-secondary
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/danyalahmed/dac-lab.git
    path: kubernetes/infra/seaweedfs/instances/secondary

  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
