desired_dns_servers: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38616430363334653363626537616139613431343631333539653138663831363237643533393233
      3762356334653561316463633965366566316664633865650a303532303835396534633661356365
      62383833353161633137376430386436376261653730393363303362363236353431626663386232
      3737626637333962610a376232393939306530336366663361623439353939373063626231326164
      6638
kubelet_csr_ip_prefixes: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32613333613162626131343933363737333338336263663133623338343162353731613764356433
      3731356538643933656132633161663363336231643231390a616438656334363063663630383231
      66303530643034646536386366646334336362613035383132373832393665383833663038373939
      6530656464643962380a363030653662333761343865326236326265393035636237303561353833
      6166
kubelet_csr_regex: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66653362393561626262643132333030666664383432313030653534626335383466346362656230
      3363376261363931656333393831386230326634373435360a373131346235363962386637653738
      63346130623033633137303665323661633739393735613937366161353137663136633765663234
      3135636632326365640a383835393935643632383331303133326430306439306261326263626231
      36353535656162613234303637373861633033663963363962313733653736633561383137653165
      3264663932613936316132663830636637363932376232613164
seaweedfs_admin_access_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36396164343137653736376237333634326564663834346334646263323866336166623432643535
      6138326266343136613337646465336133646430363363330a643563663266343532376338346662
      37343463386635336231366562333839376233396262336331636633653138653764333462313335
      3533353232363664610a393636386465386331373838333934653661376138653932633365633534
      61633435396138343361383230656364383630623663326164643038373563383730386137366166
      63636561363166323335636638373531643333396635646663663262373438376133393637353763
      61383966656639653834623934336134616564383363393937643938663830616663363330303738
      32323939343133386335
seaweedfs_admin_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35613433313538633636306432333531653234343066633561326133666465386166363938643430
      6565383131386339623539326136306665313763316666640a313564386630363436663962656463
      31643535373763313433666134313762623862376334353133333334313039323637626661396530
      3865303666376130300a316534336264666462363539613739313230313432393663613337383164
      34643964646533666234363432386236343366666333373933633134323761346539393538396133
      30326235613131303838643530333532356535626133343466393435353965663561663561353862
      63346332356133356531666239326363356261356565623531393731656231636265396130626139
      66366666386139303930
seaweedfs_secondary_admin_access_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64383932636236373833363136323133306536653133656633626636313462336530623835626430
      3038663434376531326637323362353837396239383830630a343930643566366639623833386234
      33656339373064376538356338393362393035643031396334633866386138306161336430346265
      3161656336653165380a323966356136326137666466336439333531643962653836306239633132
      64393163313663356533353231363065373839646464363438376532366638623865353633626633
      30386466663531376632643962363635356664336136366333613138643737376163346134653564
      36643631383062346562363135636539613336393564363339326331386665313237306532646162
      39323339333164663161
seaweedfs_secondary_admin_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64353538663730373437383138346533356139306538373636376262376632623565623365343862
      3334353330663331326162656139656533313338336333300a643638303064643831306163333463
      65333430616166623739623032656633653766333833656265343333313763363838656663613436
      3662396235353261360a323239623763346365626566363963386235653435653033393431653439
      31393332396363353233356163626363326634353265366464333930343163356336393236623337
      61626535613362346164643631623838353837326264353638306334333866366238366235636562
      32336636393535333464393761616235346631396364646662336664366634613434353931343030
      35643433363939313363
