kubelet_csr_ip_prefixes: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32613333613162626131343933363737333338336263663133623338343162353731613764356433
      3731356538643933656132633161663363336231643231390a616438656334363063663630383231
      66303530643034646536386366646334336362613035383132373832393665383833663038373939
      6530656464643962380a363030653662333761343865326236326265393035636237303561353833
      6166
kubelet_csr_regex: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66653362393561626262643132333030666664383432313030653534626335383466346362656230
      3363376261363931656333393831386230326634373435360a373131346235363962386637653738
      63346130623033633137303665323661633739393735613937366161353137663136633765663234
      3135636632326365640a383835393935643632383331303133326430306439306261326263626231
      36353535656162613234303637373861633033663963363962313733653736633561383137653165
      3264663932613936316132663830636637363932376232613164
seaweedfs_admin_access_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36396164343137653736376237333634326564663834346334646263323866336166623432643535
      6138326266343136613337646465336133646430363363330a643563663266343532376338346662
      37343463386635336231366562333839376233396262336331636633653138653764333462313335
      3533353232363664610a393636386465386331373838333934653661376138653932633365633534
      61633435396138343361383230656364383630623663326164643038373563383730386137366166
      63636561363166323335636638373531643333396635646663663262373438376133393637353763
      61383966656639653834623934336134616564383363393937643938663830616663363330303738
      32323939343133386335
seaweedfs_admin_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35613433313538633636306432333531653234343066633561326133666465386166363938643430
      6565383131386339623539326136306665313763316666640a313564386630363436663962656463
      31643535373763313433666134313762623862376334353133333334313039323637626661396530
      3865303666376130300a316534336264666462363539613739313230313432393663613337383164
      34643964646533666234363432386236343366666333373933633134323761346539393538396133
      30326235613131303838643530333532356535626133343466393435353965663561663561353862
      63346332356133356531666239326363356261356565623531393731656231636265396130626139
      66366666386139303930
seaweedfs_postgres_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65363034366535346637323931363132363065663038323831363462356361306263623937303937
      3935313333636333393439326635623036623465363230650a393165366261393362346166613462
      33626663636531333262653531396366653330303130663230356436663665346533303832326362
      3330343465643531360a643834616636393461313566383339326364353632616362313030383134
      65366262663962313338613632316134303233653261623637333837643865643034316265623038
      36333030306232306566396565373537343037626637333262383465626135363561623432313662
      39313539653832633531383563666633623365623937623837653737356238656362343666626161
      35306430633434646266
desired_dns_servers: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64663034326431613237616634323034316266386335626230373138313965383432376566643539
      6339306632613039336339313365386464376439613339350a376339623537346330343436363034
      37643434646631636463336365353435373230373936373165353066303461306531393261653235
      6233623132663461380a663661646633326165663431656464636666666265396231653635643934
      3137
cloudflare_api_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37646332623137363833393363373838613435383637643964616531373236653065393634643334
      3730323932653437363266333732333263303038336538330a656139306337656533643532646337
      63376561653664633264306233396233623230373331346537333339633230656266353935306130
      6236613964386136330a333664346539656361666235356632613038363239316462386133383262
      33616439646161363966383939636462353062356266323639393562663037303737626264626435
      3262316463373135663235336264643362636636326234303066
seaweedfs_metadata_backup_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37633163383263653136653639316666666637653237363430316662396331666463616166313164
      6238623336613833633261663166366433373637333134620a313435336663623765363139663334
      62356530336338383561633333323736616664643763316561373862656135393835633832643932
      6335396366303635300a333039646333633065393032666165383965343862623137326136616234
      62333634646161303732323162303532633738663665326533666332666635333435346136616333
      66643335643834376465336362636466623137346666623465326230396562376339323861306633
      63313065663536326334393239343266616336346335623562613939313537376339383266303030
      34353865656630383663
seaweedfs_vault_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33616536306539613539616265613837613535636132613331323132633163393635346135663339
      3365336537323937383161386534613639386339643065660a396134316262306138303336316633
      62363634346639626330633939393261343030303233313636616366363139643933653132356238
      6332313965626430620a396631656365353765323636656236393363336433623331633362656566
      39356430616135623861363464656137353339653064653138333439643530343363386264363465
      61356661363939303366313630316562353535303734393335336638323339623639323336313437
      34646337346466356365653466396634316662353461626263353764643332666337323530646132
      63333165643734633963
