---
galaxy_info:
  role_name: k8s_join_workers
  author: Danyal Ahmed
  description: Join worker nodes to Kubernetes cluster
  company: dac-lab
  
  license: MIT
  
  min_ansible_version: "2.15"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  
  galaxy_tags:
    - kubernetes
    - workers
    - kubeadm

dependencies: []
