apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs-operator
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/seaweedfs/operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: seaweedfs-operator
      namespace: seaweedfs-operator-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs-cluster
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/seaweedfs/cluster
  dependsOn:
    - name: seaweedfs-operator
    - name: cloudnative-pg-barman
    - name: local-path-provisioner
    - name: nfs-csi-driver
