---
galaxy_info:
  role_name: k8s_setup
  author: Danyal Ahmed
  description: Initialize Kubernetes control plane and install CNI
  company: dac-lab
  
  license: MIT
  
  min_ansible_version: "2.15"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  
  galaxy_tags:
    - kubernetes
    - kubeadm
    - calico
    - cni

dependencies: []
