apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: shared-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: seaweedfs-operator
      version: 0.1.12
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-repo
        namespace: flux-system
      interval: 1h
