---
galaxy_info:
  role_name: firewall
  author: Danyal Ahmed
  description: Configure UFW firewall rules for Kubernetes cluster
  company: dac-lab
  
  license: MIT
  
  min_ansible_version: "2.15"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  
  galaxy_tags:
    - kubernetes
    - firewall
    - ufw
    - security

dependencies: []
