apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
  - metrics-server
  - metallb/flux-kustomizations.yaml
  - cert-manager/flux-kustomizations.yaml
  - istio/flux-kustomizations.yaml