apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-operator
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/metallb/operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: metallb-speaker
      namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/metallb/config
  dependsOn:
    - name: metallb-operator
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key
