apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barman-plugin
  namespace: shared-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
        namespace: flux-system
      interval: 1h
