apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-csi-driver
  namespace: shared-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: nfs-csi-driver-repo
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: GitRepository
      name: dac-lab-private-repo
      valuesKey: kubernetes/infra/nfs-csi-driver/values.yaml
      optional: true
