apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: seaweedfs-backup
  namespace: shared-services
spec:
  schedule: "0 0 0 * * 1"  # At midnight every Monday
  backupOwnerReference: self
  cluster:
    name: seaweedfs-metadata
  method: barmanObjectStore
