apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-csi-driver
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/nfs-csi-driver/operator
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key

  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: csi-nfs-node
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: csi-nfs-controller
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-csi-driver-config
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/nfs-csi-driver/config
  dependsOn:
    - name: nfs-csi-driver
