apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./infrastructure
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./apps
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key