apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/cloudnative-pg/operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cnpg-controller-manager
      namespace: cnpg-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-barman
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/cloudnative-pg/barman
  dependsOn:
    - name: cloudnative-pg-operator
