apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/cert-manager/operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuers-and-certs
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: dac-lab-private-repo
  path: ./kubernetes/infrastructure/certs
  dependsOn:
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key
