apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatewayapi
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/istio/gatewayapi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-mesh
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/istio/mesh
  dependsOn:
    - name: gatewayapi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-gateway
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/istio/defaultgateway
  dependsOn:
    - name: istio-mesh
