apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-repo
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: GitRepository
      name: dac-lab-repo
      valuesKey: kubernetes/infrastructure/vault/values.yaml
      optional: true
