apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:q0lpPLTlDGs=,iv:XX1jLqBAEQJWOJI12UGp1JCwuBORSJbg3YqvbJ0oCfY=,tag:y5Tj38n38LChTUsjvMaweg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:FpkaQAn2BIJH6BT9HTHjQTGn43Gd3tXya1fgQJqGT9o+bUmB3SWllW0Y/6nu9pap6WzB9QgCfmFPmc845hYWnGVk0ch+iVf28TTYQ/eEgUVsBA3tS5JqTQ==,iv:IlD8oSd5Aeccs4fSxfCi7t7GFuDoPg8pL8kXLmn/+Ao=,tag:WWXwjiHo/99wFIbDFZWDww==,type:str]
kind: Secret
metadata:
    name: vault-s3-credentials
    namespace: security
type: generic
sops:
    age:
        - recipient: age17hlsg697wk7ltgxtphjzw2msa5jzgnn0f9mef66w8drpvgz6kdcqgnw8a4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb1FIcXAybUp6VHA0MEhM
            dHVxd0IvMHZGellhZm81YllKTGVmS2xwSkhBCkk2OEQrUlIyeDE0OFVEMEhCemVW
            clNMZWdmU0tTeFhBNlBDV2FoTm5mRkEKLS0tIEs5V3hSWlBuQXFJaURxcVBiYnJ5
            MFVHU01Xd2J6UWFKY2pvcUQ3cEdTWjgKygWzCEmxtjqVx74xr7UJdqN5I17kvdCT
            eSb4ljL+xcUnV4Dm9tTbmW1X4gGD8WG7qkhrce6ktJwKeyPdAvPJVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:27:07Z"
    mac: ENC[AES256_GCM,data:9eYk729ZMxglRSeD/fLStR79x1WKdEv9HcYA9Dt6N2Z0VGTi7t5oX6yEzJ5QmuhQvCWjGBktDyW0Y4Y/aP2lJ6Iim4MHZV/XQNPSWv3A6pG41rslTbS4ewohKflUniBn8TBreBsAzuh8gI/fd2AwUuIWPMA6m/OeAggyITS1tt0=,iv:ISJ3ouDtQlvAxae6MXQzrRFifjz05EKYyUOmtY8exqk=,tag:mnyTMJT4a8bZa1ht9J/ukw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
