apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-repo
  path: ./kubernetes/infrastructure/vault/operator
  decryption:
    provider: sops
    secretRef:
      name: secrets-decryption-key
  dependsOn:
    - name: seaweedfs-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-pki-integration
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  wait: true
  timeout: 5m
  force: false
  sourceRef:
    kind: GitRepository
    name: dac-lab-private-repo
  path: ./kubernetes/infra/vault-pki
  dependsOn:
    - name: vault
